name: Deploy Zola Site to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest   
    container:
      image: ghcr.io/getzola/zola:v0.19.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: recursive
          fetch-depth: 0 # Required for Zola to properly sort pages by date

      - name: Build site
        run: zola build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@0e07e157287298fa75271d3c0885b8f376a3a3ec # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'